Merge a part of reference templates to related resource templates
microsoft/FHIR-Converter pull request #229
Opened 2021-04-14 08:11 UTC by ACMoretxj

* Replace a set of reference including statements in main templates with resource templates.
* Add several new resource templates, which contained in mapping spreadsheets while not revealed before.
* Add comments in the front of template resource templates introducing reference varaibles used in this template.
* Remove condensed reference templates (approximately 31 files).

2021-04-15 00:00 UTC, ranvijaykumar requested changes

2021-04-15 02:03 UTC, ACMoretxj commented on data/Templates/Hl7v2/Resource/_Bundle.liquid
> +        {
It seems that the `Bundle.identifier` isn't an array according to the [FHIR spec](http://build.fhir.org/bundle.html).

2021-04-15 02:05 UTC, ACMoretxj commented on data/Templates/Hl7v2/Resource/_AllergyIntolerance.liquid
> +The following are references ID accepted by this template.
I've updated this sentence, thanks.

2021-04-19 02:57 UTC, BoyaWu10 commented
Let's make sure we have the same changes made in the generation tool.

2021-04-19 02:57 UTC, BoyaWu10 approved these changes

2021-04-20 06:22 UTC, ACMoretxj reviewed
The description sentences are adjusted.

2021-04-21 04:16 UTC, ranvijaykumar approved these changes

2021-04-21 04:47 UTC, merged